### ISSUE TITLE
can't create a Percentile Object

### ISSUE THREAD

**Issue by aras7** [rtidatascience/django-postgres-stats#1]
I tried to create a Percentile object like this `Percentile('my_attr', [0.25, 0.5, 0.75], continuous=True, output_field=ArrayField(models.FloatField()))` but I get the follow error:

`
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/postgres_stats/aggregates.py", line 55, in __init__
    super().__init__(expression, percentiles=percentiles, **extra)
TypeError: super() takes at least 1 argument (0 given)
`

version: `django-postgres-stats (1.0.0)`

**Comment by cndreisbach** [comment]
Unfortunately, django-postgres-stats wasn't written to support Python 2. It shouldn't be hard to, but hasn't been a priority. If you want to make it compatible, I would be glad to accept that pull request. Otherwise, it may be a while, but I'll look into it.

**Comment by aras7** [comment]
Thanks for your answer. I think with [these changes](https://github.com/rtidatascience/django-postgres-stats/pull/2) are enough.

**Comment by Seha16** [comment]
@cndreisbach it's fixed and may be closed, isn't it?
